name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: NixOS/nix-installer-action@0dd8719406e061e029989ec91b93d677d9e2bd63
        with:
          diagnostic-endpoint:
      - uses: DeterminateSystems/magic-nix-cache-action@20eea2e172f7f7487136e7a1a2f5b37aeb0e67bd
        with:
          diagnostic-endpoint:
      - name: Build tinywl
        run: |
          nix build .#tinywl --print-build-logs
